spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/franchise_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  
  jpa:
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true

logging:
  level:
    "[com.accenture.franchise]": DEBUG
    "[org.springframework.cache]": DEBUG
